### ISSUE TITLE
Mysql erros

### ISSUE THREAD

**Issue by henstercoza** [mauran/Woocommerce-delete-all-orders#2]
HI 

I get this error message when I try to run it
#1064 - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'DELETE FROM wp_woocommerce_order_items

DELETE FROM wp_posts WHERE post_type = '' at line 2 

i used this  running at the correct database 
`DELETE FROM wp_woocommerce_order_itemmeta
DELETE FROM wp_woocommerce_order_items
DELETE FROM wp_posts WHERE post_type = 'shop_order'`

**Comment by mauran** [comment]
You need to do the SQL-queries one after one. Line after line

First you run
`DELETE FROM wp_woocommerce_order_itemmeta`

then 
`DELETE FROM wp_woocommerce_order_items`

and so on. Is this working?

**Comment by henstercoza** [comment]
Thank you so much it's working .. my site has over 5200 completed orders and i need to update the word press and plugins ,, so i need to clean house fisrt ..

**Comment by mauran** [comment]
Glad that i could help!
