### ISSUE TITLE
What about wp_postmeta?

### ISSUE THREAD

**Issue by pdcable** [mauran/Woocommerce-delete-all-orders#5]

**Comment by mauran** [comment]
Hi @pdcable 
I haven't really changed this repo in 3 years, and WP is'nt my strong side. Feel free to do a PR og comment the SQL query you want included 😄

**Comment by andrija-naglic** [comment]
Hi @pdcable and @mauran 
I've created a [PR](https://github.com/mauran/Woocommerce-delete-all-orders/pull/6) which solves both wp_postmeta and wp_comments entries.

**Comment by mauran** [comment]
Hi @dev-masta. Thanks for the PR!
